### ISSUE TITLE
FoodX>> Customer>>Registration (High Priority)

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [QSPaysys1/FoodX-Testing#1]
**ISSUE:-** Customer facing issue in registration, it taking multiple attempts for registration successful.

**Comment by sankarnagarapu** [comment]
Resolved , please verify once

**Comment by srinivasmudhiraj3** [comment]
https://github.com/user-attachments/assets/93950cfd-4c62-4c31-8ed6-f43bb58f7884

After deleting the customer account and again tried to signup, This time there was no **OTP** verification and some times it was showing as **UNDEFINED**

**Comment by sankarnagarapu** [comment]
Resolved, please verify once
