### ISSUE TITLE
FoodX>> Seller app>> Location Details

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [QSPaysys1/FoodX-Testing#11]
**ISSUE:-**  After selecting a location pin in Maps, and tapping next, at least the page should scroll automatically for further details rather than scrolling manually. 

https://github.com/user-attachments/assets/9b9ea723-9692-4782-bfec-a197a5b7ccc1

**Comment by QSPaysys1** [comment]
check once

**Comment by srinivasmudhiraj3** [comment]
Issue not resolved, Can you please recheck once @QSPaysys1 


https://github.com/user-attachments/assets/de250d61-f43a-41cd-8e86-e15124056e25

**Comment by srinivasmudhiraj3** [comment]
Issue resolved
