### ISSUE TITLE
FoodX>> Customer>> Address input field in cart

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [QSPaysys1/FoodX-Testing#16]
**ISSUE:-** Address input field was not working properly like other input fields.

https://github.com/user-attachments/assets/0ac9bd50-6dab-4969-b27b-d37b532a5456

**Comment by sankarnagarapu** [comment]
could u please reupload the video , it somehow corrupted @srinivasmudhiraj3

**Comment by srinivasmudhiraj3** [comment]
https://github.com/user-attachments/assets/11abac90-5460-4ff9-97dd-582bdd360e00

**Comment by sankarnagarapu** [comment]
Resolved

**Comment by srinivasmudhiraj3** [comment]
Resolved, Thank you
