### ISSUE TITLE
FoodX>> Customer>> Map accurancy issue

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [QSPaysys1/FoodX-Testing#19]
**ISSUE:-** Even after the delivery partner has arrived to the drop location, The status was updated but the map was not working properly as shown in screenshot.

![Media (18)](https://github.com/user-attachments/assets/2475054e-86c6-47a2-b5f2-d4a025e88d44)

**Comment by sankarnagarapu** [comment]
Resolved. It is more likely a problem coming from delivery app
