### ISSUE TITLE
FoodX>> Customer>> Profile name update

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [QSPaysys1/FoodX-Testing#24]
**ISSUE:-** Once customer added a name in reciever name input in order process, it should be updated to his profile. But here it is asking every time when they make order.

https://github.com/user-attachments/assets/f61d398a-e969-4c04-96ff-30c490b490a2

**Comment by sankarnagarapu** [comment]
Resolved

**Comment by srinivasmudhiraj3** [comment]
Solved, Thank you
