### ISSUE TITLE
FoodX>> Customer app>> Product search (High Priority)

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [QSPaysys1/FoodX-Testing#4]
**ISSUE:-** While customer wants to search for "CHICKEN BIRYANI", But instead of searching as "CHICKEN BIRYANI" they just search with a word "CHICKEN" and click on search, it was taking to the Meat page for Chicken products.

**REQUIREMENT:-**  The search result for 3 tabs (Food, Meat, Fresh) should be different.

**Comment by sankarnagarapu** [comment]
Resolved, please verify once

**Comment by srinivasmudhiraj3** [comment]
Solved, Thank you
