### ISSUE TITLE
FoodX>> Customer app>> Product/Category disable (High priority)

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [QSPaysys1/FoodX-Testing#6]
**ISSUE:-** While seller disabled some **PRODUCTS** or **CATEGORY** , that Products/Category should be totally go under the Enabled Products/Categories in customer's product view.

**Comment by sankarnagarapu** [comment]
Resolved

**Comment by srinivasmudhiraj3** [comment]
https://github.com/user-attachments/assets/d71d4151-a6a7-4a72-ab19-5e3779845194

ENABLE/DISABLE for Category was working but, When the category was DISABLE, seller can't ENABLE particular products in that category. (i.e, While the Category DISABLED, the ENABLED products in that category were DISABLED).

**Comment by srinivasmudhiraj3** [comment]
ENABLE/DISABLE for Category was working but, When the category was DISABLE, seller can't ENABLE particular products in that category. (i.e, While the Category DISABLED, the ENABLED products in that category were DISABLED).


https://github.com/user-attachments/assets/35c5e7dd-cea7-48b2-b29b-f639ebdd85bb

**Comment by sankarnagarapu** [comment]
@QSPaysys1  clear the issue by categoryActive = true and product.status = 'active' in seller products list

**Comment by sankarnagarapu** [comment]
Resolved,

**Comment by srinivasmudhiraj3** [comment]
Resolved, Thank you
