### ISSUE TITLE
FoodX>> Customer app>> Distance display issue in search (High priority)

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [QSPaysys1/FoodX-Testing#7]
**ISSUE:-** In normal restaurant view in the food page, the distance of Restaurant to the customer was showing 1.1km , But when the customer was searching for a particular Restaurant, In search result the distance is showing 0.0km.

https://github.com/user-attachments/assets/be5da136-4fb3-4f0c-b3c3-7f2955a5424e

**Comment by sankarnagarapu** [comment]
Resolved. please verify

**Comment by srinivasmudhiraj3** [comment]
Verified, Thank you
